---
- name: Change Root Password
  hosts: all 
  become: true
  vars:
    new_root_password: "LinuxAdmin@50hertz" 

  tasks:
    - name: Set new root password
      user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"

